export const characterTypes = {
    SET_CHARACTER_SELECTED: 'SET_CHARACTER_SELECTED',
    CHARACTER_START: 'CHARACTER_START',
    CHARACTER_END: 'CHARACTER_END',
    CHARACTER_ERROR: 'CHARACTER_END',
}